### ISSUE TITLE
License

### ISSUE THREAD

**Issue by apawlik** [PawseySC/pawseysc.github.io#9]
Hello from across the ditch! 

I was wondering what license this repo is under as I really like the layout and was hoping to adapt it for https://github.com/manaakiwhenua/ GH pages.

**Comment by marcodelapierre** [comment]
hi Aleksandra, glad you like it! kudos to @ratkinson0405 for its creation.
I'll check within the team and get back to you soon on the license.

**Comment by marcodelapierre** [comment]
Dear Aleksandra, Rob has added licensing to the project, under the terms of the MIT License.
I am positive this will fit your needs :) 

Best, Marco

**Comment by apawlik** [comment]
Thank you so much!
